torch.nn:
- Identity
- Linear
- Conv1d
- Conv2d
- Conv3d
- ConvTranspose1d
- ConvTranspose2d
- ConvTranspose3d
- Threshold
- ReLU
- Hardtanh
- ReLU6
- Sigmoid
- Tanh
- Softmax
- Softmax2d
- LogSoftmax
- ELU
- SELU
- CELU
- GLU
- GELU
- Hardshrink
- LeakyReLU
- LogSigmoid
- Softplus
- Softshrink
- MultiheadAttention
- PReLU
- Softsign
- Softmin
- Tanhshrink
- RReLU
- L1Loss
- NLLLoss
- KLDivLoss
- MSELoss
- BCELoss
- BCEWithLogitsLoss
- NLLLoss2d
- PoissonNLLLoss
- CosineEmbeddingLoss
- CTCLoss
- HingeEmbeddingLoss
- MarginRankingLoss
- MultiLabelMarginLoss
- MultiLabelSoftMarginLoss
- MultiMarginLoss
- SmoothL1Loss
- GaussianNLLLoss
- HuberLoss
- SoftMarginLoss
- CrossEntropyLoss
- AvgPool1d
- AvgPool2d
- AvgPool3d
- MaxPool1d
- MaxPool2d
- MaxPool3d
- MaxUnpool1d
- MaxUnpool2d
- MaxUnpool3d
- FractionalMaxPool2d
- FractionalMaxPool3d
- LPPool1d
- LPPool2d
- LocalResponseNorm
- BatchNorm1d
- BatchNorm2d
- BatchNorm3d
- InstanceNorm1d
- InstanceNorm2d
- InstanceNorm3d
- LayerNorm
- GroupNorm
- SyncBatchNorm
- Dropout
- Dropout2d
- Dropout3d
- AlphaDropout
- FeatureAlphaDropout
- ReflectionPad1d
- ReflectionPad2d
- ReflectionPad3d
- ReplicationPad2d
- ReplicationPad1d
- ReplicationPad3d
- CrossMapLRN2d
- Embedding
- EmbeddingBag
- RNNBase
- RNN
- LSTM
- GRU
- RNNCellBase
- RNNCell
- LSTMCell
- GRUCell
- PixelShuffle
- PixelUnshuffle
- Upsample
- UpsamplingNearest2d
- UpsamplingBilinear2d
- PairwiseDistance
- AdaptiveMaxPool1d
- AdaptiveMaxPool2d
- AdaptiveMaxPool3d
- AdaptiveAvgPool1d
- AdaptiveAvgPool2d
- AdaptiveAvgPool3d
- TripletMarginLoss
- ZeroPad2d
- ConstantPad1d
- ConstantPad2d
- ConstantPad3d
- Bilinear
- CosineSimilarity
- Unfold
- Fold
- AdaptiveLogSoftmaxWithLoss
- Transformer
- LazyLinear
- LazyConv1d
- LazyConv2d
- LazyConv3d
- LazyConvTranspose1d
- LazyConvTranspose2d
- LazyConvTranspose3d
- LazyBatchNorm1d
- LazyBatchNorm2d
- LazyBatchNorm3d
- LazyInstanceNorm1d
- LazyInstanceNorm2d
- LazyInstanceNorm3d
- Flatten
- Unflatten
- Hardsigmoid
- Hardswish
- SiLU
- Mish
- TripletMarginWithDistanceLoss
- ChannelShuffle
- UninitializedParameter
- UninitializedBuffer
torch.quantization:
- QuantStub
- DeQuantStub
- QuantWrapper
torchvision.ops:
- DeformConv2d
- FrozenBatchNorm2d
- MultiScaleRoIAlign
- PSRoIAlign
- PSRoIPool
- RoIAlign
- RoIPool
- StochasticDepth
