torch:
- _assert_async
- _rowwise_prune
- abs
- absolute
- acos
- acosh
- adaptive_avg_pool1d
- adaptive_max_pool1d
- add
- addbmm
- addcdiv
- addcmul
- addmm
- addmv
- addr
- affine_grid_generator
- all
- allclose
- alpha_dropout
- amax
- amin
- aminmax
- angle
- any
- arccos
- arccosh
- arcsin
- arcsinh
- arctan
- arctanh
- argmax
- argmin
- argsort
- asin
- asinh
- atan
- atan2
- atanh
- atleast_1d
- atleast_2d
- atleast_3d
- avg_pool1d
- baddbmm
- batch_norm
- batch_norm_backward_elemt
- batch_norm_backward_reduce
- batch_norm_elemt
- batch_norm_gather_stats
- batch_norm_gather_stats_with_counts
- batch_norm_stats
- batch_norm_update_stats
- bernoulli
- bilinear
- binary_cross_entropy_with_logits
- bincount
- binomial
- bitwise_and
- bitwise_left_shift
- bitwise_not
- bitwise_or
- bitwise_right_shift
- bitwise_xor
- block_diag
- bmm
- broadcast_tensors
- broadcast_to
- bucketize
- cartesian_prod
- cat
- cdist
- ceil
- celu
- chain_matmul
- channel_shuffle
- cholesky
- cholesky_inverse
- cholesky_solve
- choose_qparams_optimized
- chunk
- clamp
- clamp_max
- clamp_min
- clip
- clone
- column_stack
- combinations
- complex
- concat
- conj
- conj_physical
- constant_pad_nd
- conv1d
- conv2d
- conv3d
- conv_tbc
- conv_transpose1d
- conv_transpose2d
- conv_transpose3d
- convolution
- copysign
- corrcoef
- cos
- cosh
- cosine_embedding_loss
- cosine_similarity
- count_nonzero
- cov
- cross
- ctc_loss
- cummax
- cummin
- cumprod
- cumsum
- cumulative_trapezoid
- deg2rad
- dequantize
- det
- detach
- diag
- diag_embed
- diagflat
- diagonal
- diff
- digamma
- dist
- div
- divide
- dot
- dropout
- dsmm
- dsplit
- dstack
- eig
- einsum
- embedding
- embedding_bag
- empty_like
- eq
- equal
- erf
- erfc
- erfinv
- exp
- exp2
- expm1
- fake_quantize_per_channel_affine
- fake_quantize_per_tensor_affine
- fbgemm_linear_fp16_weight
- fbgemm_linear_fp16_weight_fp32_activation
- fbgemm_linear_int8_weight
- fbgemm_linear_int8_weight_fp32_activation
- fbgemm_linear_quantize_weight
- fbgemm_pack_gemm_matrix_fp16
- fbgemm_pack_quantized_matrix
- feature_alpha_dropout
- feature_dropout
- fix
- flatten
- flip
- fliplr
- flipud
- float_power
- floor
- floor_divide
- fmax
- fmin
- fmod
- frac
- frexp
- frobenius_norm
- full_like
- fused_moving_avg_obs_fake_quant
- gather
- gcd
- ge
- geqrf
- ger
- gradient
- greater
- greater_equal
- grid_sampler
- grid_sampler_2d
- grid_sampler_3d
- group_norm
- gru
- gru_cell
- gt
- hardshrink
- heaviside
- hinge_embedding_loss
- histc
- histogram
- hsmm
- hsplit
- hspmm
- hstack
- hypot
- i0
- igamma
- igammac
- imag
- index_add
- index_copy
- index_fill
- index_put
- index_select
- inner
- instance_norm
- int_repr
- inverse
- is_complex
- is_conj
- is_distributed
- is_floating_point
- is_inference
- is_neg
- is_nonzero
- is_same_size
- is_signed
- isclose
- isfinite
- isin
- isinf
- isnan
- isneginf
- isposinf
- isreal
- istft
- kl_div
- kron
- kthvalue
- layer_norm
- lcm
- ldexp
- le
- lerp
- less
- less_equal
- lgamma
- lobpcg
- log
- log10
- log1p
- log2
- log_softmax
- logaddexp
- logaddexp2
- logcumsumexp
- logdet
- logical_and
- logical_not
- logical_or
- logical_xor
- logit
- logsumexp
- lstm
- lstm_cell
- lstsq
- lt
- lu_solve
- lu_unpack
- margin_ranking_loss
- masked_fill
- masked_scatter
- masked_select
- matmul
- matrix_exp
- matrix_power
- matrix_rank
- max
- max_pool1d
- max_pool1d_with_indices
- max_pool2d
- max_pool3d
- maximum
- mean
- median
- meshgrid
- min
- minimum
- miopen_batch_norm
- miopen_convolution
- miopen_convolution_transpose
- miopen_depthwise_convolution
- miopen_rnn
- mm
- mode
- moveaxis
- movedim
- msort
- mul
- multinomial
- multiply
- mv
- mvlgamma
- nan_to_num
- nanmean
- nanmedian
- nanquantile
- nansum
- narrow
- narrow_copy
- native_batch_norm
- native_group_norm
- native_layer_norm
- native_norm
- ne
- neg
- negative
- nextafter
- nonzero
- norm
- norm_except_dim
- not_equal
- nuclear_norm
- numel
- ones_like
- orgqr
- ormqr
- outer
- pairwise_distance
- pdist
- permute
- pinverse
- pixel_shuffle
- pixel_unshuffle
- poisson
- poisson_nll_loss
- polar
- polygamma
- positive
- pow
- prelu
- prod
- put
- q_per_channel_axis
- q_per_channel_scales
- q_per_channel_zero_points
- q_scale
- q_zero_point
- qr
- quantile
- quantize_per_channel
- quantize_per_tensor
- quantized_batch_norm
- quantized_gru_cell
- quantized_lstm_cell
- quantized_max_pool1d
- quantized_max_pool2d
- quantized_rnn_relu_cell
- quantized_rnn_tanh_cell
- rad2deg
- rand_like
- randint_like
- randn_like
- ravel
- real
- reciprocal
- relu
- remainder
- renorm
- repeat_interleave
- reshape
- resolve_conj
- resolve_neg
- rnn_relu
- rnn_relu_cell
- rnn_tanh
- rnn_tanh_cell
- roll
- rot90
- round
- row_stack
- rrelu
- rsqrt
- rsub
- saddmm
- scatter
- scatter_add
- searchsorted
- segment_reduce
- select
- selu
- sgn
- sigmoid
- sign
- signbit
- sin
- sinc
- sinh
- slogdet
- smm
- softmax
- solve
- sort
- split
- split_with_sizes
- spmm
- sqrt
- square
- squeeze
- sspaddmm
- stack
- std
- std_mean
- stft
- sub
- subtract
- sum
- svd
- swapaxes
- swapdims
- symeig
- t
- take
- take_along_dim
- tan
- tanh
- tensor_split
- tensordot
- threshold
- tile
- topk
- trace
- transpose
- trapezoid
- trapz
- triangular_solve
- tril
- triplet_margin_loss
- triu
- true_divide
- trunc
- unbind
- unique_consecutive
- unsafe_chunk
- unsafe_split
- unsafe_split_with_sizes
- unsqueeze
- var
- var_mean
- vdot
- view_as_complex
- view_as_real
- vsplit
- vstack
- where
- xlogy
- zeros_like
torch.Tensor:
- __abs__
- __add__
- __and__
- __array__
- __array_wrap__
- __bool__
- __complex__
- __contains__
- __deepcopy__
- __delitem__
- __div__
- __dlpack__
- __dlpack_device__
- __eq__
- __float__
- __floordiv__
- __format__
- __ge__
- __getitem__
- __gt__
- __hash__
- __iadd__
- __iand__
- __idiv__
- __ifloordiv__
- __ilshift__
- __imod__
- __imul__
- __index__
- __int__
- __invert__
- __ior__
- __ipow__
- __irshift__
- __isub__
- __itruediv__
- __ixor__
- __le__
- __len__
- __long__
- __lshift__
- __lt__
- __matmul__
- __mod__
- __mul__
- __ne__
- __neg__
- __nonzero__
- __or__
- __pos__
- __pow__
- __radd__
- __rand__
- __rdiv__
- __reduce_ex__
- __repr__
- __reversed__
- __rfloordiv__
- __rlshift__
- __rmatmul__
- __rmod__
- __rmul__
- __ror__
- __rpow__
- __rrshift__
- __rshift__
- __rsub__
- __rtruediv__
- __rxor__
- __setitem__
- __setstate__
- __sub__
- __truediv__
- __xor__
- _coalesced_
- _dimI
- _dimV
- _indices
- _is_view
- _nnz
- _update_names
- _values
- abs
- abs_
- absolute
- absolute_
- acos
- acos_
- acosh
- acosh_
- add
- add_
- addbmm
- addbmm_
- addcdiv
- addcdiv_
- addcmul
- addcmul_
- addmm
- addmm_
- addmv
- addmv_
- addr
- addr_
- align_as
- align_to
- all
- allclose
- amax
- amin
- aminmax
- angle
- any
- apply_
- arccos
- arccos_
- arccosh
- arccosh_
- arcsin
- arcsin_
- arcsinh
- arcsinh_
- arctan
- arctan_
- arctanh
- arctanh_
- argmax
- argmin
- argsort
- as_strided
- as_strided_
- asin
- asin_
- asinh
- asinh_
- atan
- atan2
- atan2_
- atan_
- atanh
- atanh_
- backward
- baddbmm
- baddbmm_
- bernoulli
- bernoulli_
- bfloat16
- bincount
- bitwise_and
- bitwise_and_
- bitwise_left_shift
- bitwise_left_shift_
- bitwise_not
- bitwise_not_
- bitwise_or
- bitwise_or_
- bitwise_right_shift
- bitwise_right_shift_
- bitwise_xor
- bitwise_xor_
- bmm
- bool
- broadcast_to
- byte
- cauchy_
- cdouble
- ceil
- ceil_
- cfloat
- char
- cholesky
- cholesky_inverse
- cholesky_solve
- chunk
- clamp
- clamp_
- clamp_max
- clamp_max_
- clamp_min
- clamp_min_
- clip
- clip_
- clone
- coalesce
- col_indices
- conj
- conj_physical
- conj_physical_
- contiguous
- copy_
- copysign
- copysign_
- corrcoef
- cos
- cos_
- cosh
- cosh_
- count_nonzero
- cov
- cpu
- cross
- crow_indices
- cuda
- cummax
- cummin
- cumprod
- cumprod_
- cumsum
- cumsum_
- data_ptr
- deg2rad
- deg2rad_
- dense_dim
- dequantize
- det
- detach
- detach_
- diag
- diag_embed
- diagflat
- diagonal
- diff
- digamma
- digamma_
- dim
- dist
- div
- div_
- divide
- divide_
- dot
- double
- dsplit
- eig
- element_size
- eq
- eq_
- equal
- erf
- erf_
- erfc
- erfc_
- erfinv
- erfinv_
- exp
- exp2
- exp2_
- exp_
- expand
- expand_as
- expm1
- expm1_
- exponential_
- fill_
- fill_diagonal_
- fix
- fix_
- flatten
- flip
- fliplr
- flipud
- float
- float_power
- float_power_
- floor
- floor_
- floor_divide
- floor_divide_
- fmax
- fmin
- fmod
- fmod_
- frac
- frac_
- frexp
- gather
- gcd
- gcd_
- ge
- ge_
- geometric_
- geqrf
- ger
- get_device
- greater
- greater_
- greater_equal
- greater_equal_
- gt
- gt_
- half
- hardshrink
- has_names
- heaviside
- heaviside_
- histc
- histogram
- hsplit
- hypot
- hypot_
- i0
- i0_
- igamma
- igamma_
- igammac
- igammac_
- index_add
- index_add_
- index_copy
- index_copy_
- index_fill
- index_fill_
- index_put
- index_put_
- index_select
- indices
- inner
- int
- int_repr
- inverse
- is_coalesced
- is_complex
- is_conj
- is_contiguous
- is_distributed
- is_floating_point
- is_inference
- is_neg
- is_nonzero
- is_pinned
- is_same_size
- is_set_to
- is_shared
- is_signed
- isclose
- isfinite
- isinf
- isnan
- isneginf
- isposinf
- isreal
- istft
- item
- kron
- kthvalue
- lcm
- lcm_
- ldexp
- ldexp_
- le
- le_
- lerp
- lerp_
- less
- less_
- less_equal
- less_equal_
- lgamma
- lgamma_
- log
- log10
- log10_
- log1p
- log1p_
- log2
- log2_
- log_
- log_normal_
- log_softmax
- logaddexp
- logaddexp2
- logcumsumexp
- logdet
- logical_and
- logical_and_
- logical_not
- logical_not_
- logical_or
- logical_or_
- logical_xor
- logical_xor_
- logit
- logit_
- logsumexp
- long
- lstsq
- lt
- lt_
- lu
- lu_solve
- map2_
- map_
- masked_fill
- masked_fill_
- masked_scatter
- masked_scatter_
- masked_select
- matmul
- matrix_exp
- matrix_power
- max
- maximum
- mean
- median
- min
- minimum
- mm
- mode
- moveaxis
- movedim
- msort
- mul
- mul_
- multinomial
- multiply
- multiply_
- mv
- mvlgamma
- mvlgamma_
- nan_to_num
- nan_to_num_
- nanmean
- nanmedian
- nanquantile
- nansum
- narrow
- narrow_copy
- ndimension
- ne
- ne_
- neg
- neg_
- negative
- negative_
- nelement
- nextafter
- nextafter_
- nonzero
- norm
- normal_
- not_equal
- not_equal_
- numel
- numpy
- orgqr
- ormqr
- outer
- permute
- pin_memory
- pinverse
- polygamma
- polygamma_
- positive
- pow
- pow_
- prelu
- prod
- put
- put_
- q_per_channel_axis
- q_per_channel_scales
- q_per_channel_zero_points
- q_scale
- q_zero_point
- qr
- qscheme
- quantile
- rad2deg
- rad2deg_
- random_
- ravel
- reciprocal
- reciprocal_
- record_stream
- refine_names
- register_hook
- relu
- relu_
- remainder
- remainder_
- rename
- rename_
- renorm
- renorm_
- repeat
- repeat_interleave
- requires_grad_
- reshape
- reshape_as
- resize
- resize_
- resize_as
- resize_as_
- resolve_conj
- resolve_neg
- retain_grad
- roll
- rot90
- round
- round_
- rsqrt
- rsqrt_
- scatter
- scatter_
- scatter_add
- scatter_add_
- select
- set_
- sgn
- sgn_
- share_memory_
- short
- sigmoid
- sigmoid_
- sign
- sign_
- signbit
- sin
- sin_
- sinc
- sinc_
- sinh
- sinh_
- size
- slogdet
- smm
- softmax
- solve
- sort
- sparse_dim
- sparse_mask
- sparse_resize_
- sparse_resize_and_clear_
- split
- split_with_sizes
- sqrt
- sqrt_
- square
- square_
- squeeze
- squeeze_
- sspaddmm
- std
- stft
- storage
- storage_offset
- storage_type
- sub
- sub_
- subtract
- subtract_
- sum
- sum_to_size
- svd
- swapaxes
- swapaxes_
- swapdims
- swapdims_
- symeig
- t
- t_
- take
- take_along_dim
- tan
- tan_
- tanh
- tanh_
- tensor_split
- tile
- to
- to_dense
- to_mkldnn
- to_sparse
- tolist
- topk
- trace
- transpose
- transpose_
- triangular_solve
- tril
- tril_
- triu
- triu_
- true_divide
- true_divide_
- trunc
- trunc_
- type
- type_as
- unbind
- unfold
- uniform_
- unique
- unique_consecutive
- unsafe_chunk
- unsafe_split
- unsafe_split_with_sizes
- unsqueeze
- unsqueeze_
- values
- var
- vdot
- view
- view_as
- vsplit
- where
- xlogy
- xlogy_
- xpu
- zero_
torch._lobpcg:
- lobpcg
torch._lowrank:
- pca_lowrank
- svd_lowrank
torch.fft:
- fft
- fft2
- fft_fft
- fft_fft2
- fft_fftn
- fft_fftshift
- fft_hfft
- fft_ifft
- fft_ifft2
- fft_ifftn
- fft_ifftshift
- fft_ihfft
- fft_irfft
- fft_irfft2
- fft_irfftn
- fft_rfft
- fft_rfft2
- fft_rfftn
- fftn
- fftshift
- hfft
- ifft
- ifft2
- ifftn
- ifftshift
- ihfft
- irfft
- irfft2
- irfftn
- rfft
- rfft2
- rfftn
torch.functional:
- _consecutive_return_inverse_false
- _consecutive_return_inverse_true
- _return_inverse_false
- _return_inverse_true
- atleast_1d
- atleast_2d
- atleast_3d
- block_diag
- broadcast_tensors
- cartesian_prod
- cdist
- chain_matmul
- einsum
- istft
- lu
- meshgrid
- norm
- pca_lowrank
- split
- stft
- svd_lowrank
- tensordot
- unique
- unique_consecutive
torch.linalg:
- cholesky
- cholesky_ex
- cond
- det
- eig
- eigh
- eigvals
- eigvalsh
- householder_product
- inv
- inv_ex
- linalg_cholesky
- linalg_cholesky_ex
- linalg_cond
- linalg_det
- linalg_eig
- linalg_eigh
- linalg_eigvals
- linalg_eigvalsh
- linalg_householder_product
- linalg_inv
- linalg_inv_ex
- linalg_lstsq
- linalg_matmul
- linalg_matrix_norm
- linalg_matrix_power
- linalg_matrix_rank
- linalg_multi_dot
- linalg_norm
- linalg_pinv
- linalg_qr
- linalg_slogdet
- linalg_solve
- linalg_svd
- linalg_svdvals
- linalg_tensorinv
- linalg_tensorsolve
- linalg_vector_norm
- lstsq
- matmul
- matrix_norm
- matrix_power
- matrix_rank
- multi_dot
- norm
- pinv
- qr
- slogdet
- solve
- svd
- svdvals
- tensorinv
- tensorsolve
- vector_norm
torch.nn.functional:
- _pad
- _threshold
- adaptive_avg_pool1d
- adaptive_avg_pool2d
- adaptive_avg_pool3d
- adaptive_max_pool1d
- adaptive_max_pool1d_with_indices
- adaptive_max_pool2d
- adaptive_max_pool2d_with_indices
- adaptive_max_pool3d
- adaptive_max_pool3d_with_indices
- affine_grid
- alpha_dropout
- avg_pool1d
- avg_pool2d
- avg_pool3d
- batch_norm
- bilinear
- binary_cross_entropy
- binary_cross_entropy_with_logits
- celu
- channel_shuffle
- conv1d
- conv2d
- conv3d
- conv_tbc
- conv_transpose1d
- conv_transpose2d
- conv_transpose3d
- cosine_embedding_loss
- cosine_similarity
- cross_entropy
- ctc_loss
- dropout
- dropout2d
- dropout3d
- elu
- embedding
- embedding_bag
- feature_alpha_dropout
- fold
- fractional_max_pool2d
- fractional_max_pool2d_with_indices
- fractional_max_pool3d
- fractional_max_pool3d_with_indices
- gaussian_nll_loss
- gelu
- glu
- grid_sample
- group_norm
- gumbel_softmax
- hardshrink
- hardsigmoid
- hardswish
- hardtanh
- hinge_embedding_loss
- huber_loss
- instance_norm
- interpolate
- kl_div
- l1_loss
- layer_norm
- leaky_relu
- linear
- local_response_norm
- log_sigmoid
- log_softmax
- logsigmoid
- lp_pool1d
- lp_pool2d
- margin_ranking_loss
- max_pool1d
- max_pool1d_with_indices
- max_pool2d
- max_pool2d_with_indices
- max_pool3d
- max_pool3d_with_indices
- max_unpool1d
- max_unpool2d
- max_unpool3d
- mish
- mse_loss
- multi_head_attention_forward
- multi_margin_loss
- multilabel_margin_loss
- multilabel_soft_margin_loss
- nll_loss
- normalize
- one_hot
- pad
- pairwise_distance
- pdist
- pixel_shuffle
- pixel_unshuffle
- poisson_nll_loss
- prelu
- relu
- relu6
- rrelu
- selu
- sigmoid
- silu
- smooth_l1_loss
- soft_margin_loss
- softmax
- softmin
- softplus
- softshrink
- softsign
- tanh
- tanhshrink
- threshold
- triplet_margin_loss
- triplet_margin_with_distance_loss
- unfold
- upsample
- upsample_bilinear
- upsample_nearest
torch.special:
- digamma
- entr
- erf
- erfc
- erfcx
- erfinv
- exp2
- expit
- expm1
- gammainc
- gammaincc
- gammaln
- i0
- i0e
- i1
- i1e
- log1p
- log_softmax
- logit
- logsumexp
- multigammaln
- ndtr
- ndtri
- polygamma
- psi
- round
- sinc
- special_digamma
- special_entr
- special_erf
- special_erfc
- special_erfcx
- special_erfinv
- special_exp2
- special_expit
- special_expm1
- special_gammainc
- special_gammaincc
- special_gammaln
- special_i0
- special_i0e
- special_i1
- special_i1e
- special_log1p
- special_log_softmax
- special_logit
- special_logsumexp
- special_multigammaln
- special_ndtr
- special_ndtri
- special_polygamma
- special_psi
- special_round
- special_sinc
- special_xlog1py
- special_xlogy
- special_zeta
- xlog1py
- xlogy
- zeta
torchvision.ops:
- batched_nms
- box_area
- box_convert
- box_iou
- clip_boxes_to_image
- deform_conv2d
- generalized_box_iou
- masks_to_boxes
- nms
- ps_roi_align
- ps_roi_pool
- remove_small_boxes
- roi_align
- roi_pool
- sigmoid_focal_loss
- stochastic_depth
